apiVersion: v1
kind: Service
metadata:
  name: demo-app-bindshell
  namespace: dev
spec:
  selector:
    app: demo-app-insecure-config
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: webapp
  - protocol: TCP
    port: 9999
    targetPort: 9999
    name: bindshell
