apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-insecure-config
  namespace: dev
  labels:
    app: demo-app-insecure-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-insecure-config
  template:
    metadata:
      labels:
        app: demo-app-insecure-config
    spec:
      containers:
      - name: demo-app-insecure-config
        image: larslefebvre/h4cking-workshop-demo-app:867361
        imagePullPolicy: IfNotPresent
      serviceAccountName: demo-app-insecure-config