apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app-insecure-config
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: demo-app-insecure-config
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "watch", "list", "exec","patch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: [ "get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-app-insecure-config
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-app-insecure-config
subjects:
- kind: ServiceAccount
  name: demo-app-insecure-config
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo-app-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes","pods",pods/exec"]
  verbs: ["get", "watch", "list","exec","create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-app-insecure-config-binding
subjects:
- kind: ServiceAccount
  name: demo-app-insecure-config
  namespace: default
roleRef:
  kind: ClusterRole
  name: demo-app-cluster-role
  apiGroup: rbac.authorization.k8s.io