apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
  namespace: demo-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: evil-sa
  namespace: evil-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: demo-ns
  name: demo-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "watch", "list", "exec","patch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: [ "get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-role-binding
  namespace: demo-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-role
subjects:
- kind: ServiceAccount
  name: demo-sa
  namespace: demo-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes","pods",pods/exec"]
  verbs: ["get", "watch", "list","exec","create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: demo-sa
  namespace: demo-ns
roleRef:
  kind: ClusterRole
  name: demo-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role-secrets
rules:
- apiGroups: [""]
  resources: ["pods","secrets"]
  verbs: ["create", "get", "watch", "list", "exec","patch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: [ "get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: evil-cluster-role-binding-secrets
subjects:
- kind: ServiceAccount
  name: evil-sa
  namespace: evil-ns
roleRef:
  kind: ClusterRole
  name: cluster-role-secrets
  apiGroup: rbac.authorization.k8s.io  